vcap:
  services:
    p-mysql:
    - name: mySql1
      label: p-mysql
      tags:
      - mysql
      - relational
      plan: 100mb-dev
      credentials:
        hostname: 192.168.0.97
        port: 3306
        name: cf_0f5dda44_e678_4727_993f_30e6d455cc31
        username: 9vD0Mtk3wFFuaaaY
        password: Cjn4HsAiKV8sImst
        uri: mysql://9vD0Mtk3wFFuaaaY:Cjn4HsAiKV8sImst@192.168.0.97:3306/cf_0f5dda44_e678_4727_993f_30e6d455cc31?reconnect=true
        jdbcUrl: jdbc:mysql://192.168.0.97:3306/cf_0f5dda44_e678_4727_993f_30e6d455cc31?user=9vD0Mtk3wFFuaaaY&password=Cjn4HsAiKV8sImst
    p-redis:
    - name: autosource_redis_cache
      label: p-redis
      tags:
      - pivotal
      - redis
      plan: share-dev
      provider: 
      volume_mounts: []
      syslog_drain_url: 
      credentials:
        hostname: 10.66.32.54
        port: 6379
        password: 4254bd8b-7f83-4a8d-8f38-8206a9d7a9f7
    p-rabbitmq:
    - credentials:
        http_api_uris:
        - https://03c7a684-6ff1-4bd0-ad45-d10374ffb2af:l5oq2q0unl35s6urfsuib0jvpo@pivotal-rabbitmq.system.testcloud.com/api/
        ssl: false
        dashboard_url: https://pivotal-rabbitmq.system.testcloud.com/#/login/03c7a684-6ff1-4bd0-ad45-d10374ffb2af/l5oq2q0unl35s6urfsuib0jvpo
        password: l5oq2q0unl35s6urfsuib0jvpo
        protocols:
          management:
            path: "/api/"
            ssl: false
            hosts:
            - 192.168.0.81
            password: l5oq2q0unl35s6urfsuib0jvpo
            username: 03c7a684-6ff1-4bd0-ad45-d10374ffb2af
            port: 15672
            host: 192.168.0.81
            uri: https://03c7a684-6ff1-4bd0-ad45-d10374ffb2af:l5oq2q0unl35s6urfsuib0jvpo@192.168.0.81:15672/api/
            uris:
            - https://03c7a684-6ff1-4bd0-ad45-d10374ffb2af:l5oq2q0unl35s6urfsuib0jvpo@192.168.0.81:15672/api/
          amqp:
            vhost: fb03d693-91fe-4dc5-8203-ff7a6390df66
            username: 03c7a684-6ff1-4bd0-ad45-d10374ffb2af
            password: l5oq2q0unl35s6urfsuib0jvpo
            port: 5672
            host: 192.168.0.81
            hosts:
            - 192.168.0.81
            ssl: false
            uri: amqp://03c7a684-6ff1-4bd0-ad45-d10374ffb2af:l5oq2q0unl35s6urfsuib0jvpo@192.168.0.81:5672/fb03d693-91fe-4dc5-8203-ff7a6390df66
            uris:
            - amqp://03c7a684-6ff1-4bd0-ad45-d10374ffb2af:l5oq2q0unl35s6urfsuib0jvpo@192.168.0.81:5672/fb03d693-91fe-4dc5-8203-ff7a6390df66
        username: 03c7a684-6ff1-4bd0-ad45-d10374ffb2af
        hostname: 192.168.0.81
        hostnames:
        - 192.168.0.81
        vhost: fb03d693-91fe-4dc5-8203-ff7a6390df66
        http_api_uri: https://03c7a684-6ff1-4bd0-ad45-d10374ffb2af:l5oq2q0unl35s6urfsuib0jvpo@pivotal-rabbitmq.system.testcloud.com/api/
        uri: amqp://03c7a684-6ff1-4bd0-ad45-d10374ffb2af:l5oq2q0unl35s6urfsuib0jvpo@192.168.0.81/fb03d693-91fe-4dc5-8203-ff7a6390df66
        uris:
        - amqp://03c7a684-6ff1-4bd0-ad45-d10374ffb2af:l5oq2q0unl35s6urfsuib0jvpo@192.168.0.81/fb03d693-91fe-4dc5-8203-ff7a6390df66
      syslog_drain_url: 
      label: p-rabbitmq
      provider: 
      plan: standard
      name: spring-cloud-broker-rmq
      tags:
      - rabbitmq
      - messaging
      - message-queue
      - amqp
      - stomp
      - mqtt
      - pivotal
    p-circuit-breaker-dashboard:
    - credentials:
        stream: https://turbine-5ac7e504-3ca5-4f02-9302-d5554c059043.apps.testcloud.com
        amqp:
          http_api_uris:
          - https://a0f39f25-28a2-438e-a0e7-6c09d6d34dbd:1clgf5ipeop36437dmr2em4duk@pivotal-rabbitmq.system.testcloud.com/api/
          ssl: false
          dashboard_url: https://pivotal-rabbitmq.system.testcloud.com/#/login/a0f39f25-28a2-438e-a0e7-6c09d6d34dbd/1clgf5ipeop36437dmr2em4duk
          password: 1clgf5ipeop36437dmr2em4duk
          protocols:
            amqp:
              vhost: 06f0b204-9f95-4829-a662-844d3c3d6120
              username: a0f39f25-28a2-438e-a0e7-6c09d6d34dbd
              password: 1clgf5ipeop36437dmr2em4duk
              port: 5672
              host: 192.168.1.55
              hosts:
              - 192.168.1.55
              ssl: false
              uri: amqp://a0f39f25-28a2-438e-a0e7-6c09d6d34dbd:1clgf5ipeop36437dmr2em4duk@192.168.1.55:5672/06f0b204-9f95-4829-a662-844d3c3d6120
              uris:
              - amqp://a0f39f25-28a2-438e-a0e7-6c09d6d34dbd:1clgf5ipeop36437dmr2em4duk@192.168.1.55:5672/06f0b204-9f95-4829-a662-844d3c3d6120
            management:
              path: "/api/"
              ssl: false
              hosts:
              - 192.168.1.55
              password: 1clgf5ipeop36437dmr2em4duk
              username: a0f39f25-28a2-438e-a0e7-6c09d6d34dbd
              port: 15672
              host: 192.168.1.55
              uri: https://a0f39f25-28a2-438e-a0e7-6c09d6d34dbd:1clgf5ipeop36437dmr2em4duk@192.168.1.55:15672/api/
              uris:
              - https://a0f39f25-28a2-438e-a0e7-6c09d6d34dbd:1clgf5ipeop36437dmr2em4duk@192.168.1.55:15672/api/
          username: a0f39f25-28a2-438e-a0e7-6c09d6d34dbd
          hostname: 192.168.1.55
          hostnames:
          - 192.168.1.55
          vhost: 06f0b204-9f95-4829-a662-844d3c3d6120
          http_api_uri: https://a0f39f25-28a2-438e-a0e7-6c09d6d34dbd:1clgf5ipeop36437dmr2em4duk@pivotal-rabbitmq.system.testcloud.com/api/
          uri: amqp://a0f39f25-28a2-438e-a0e7-6c09d6d34dbd:1clgf5ipeop36437dmr2em4duk@192.168.1.55/06f0b204-9f95-4829-a662-844d3c3d6120
          uris:
          - amqp://a0f39f25-28a2-438e-a0e7-6c09d6d34dbd:1clgf5ipeop36437dmr2em4duk@192.168.1.55/06f0b204-9f95-4829-a662-844d3c3d6120
        dashboard: https://hystrix-5ac7e504-3ca5-4f02-9302-d5554c059043.apps.testcloud.com
      syslog_drain_url: 
      volume_mounts: []
      label: p-circuit-breaker-dashboard
      provider: 
      plan: standard
      name: myHystrixService
      tags:
      - circuit-breaker
      - hystrix-amqp
      - spring-cloud